#!/bin/bash
export LC_CTYPE=en_GB.UTF-8

if tty -s; then
    PS1="[\[$(tput bold)$(tput setaf 4)\]\u\[$(tput sgr0)\]@\h \[$(tput bold)\]\W\[$(tput sgr0)\]]\$ "
else
    PS1="[\u@\h \W]\$ "
fi

alias ll="ls -l --color=always"
alias grep="grep --color=always"
alias less="less_highlight"

PATH=/usr/lib/ccache:$PATH:~/bin:~/tool/smartgit/bin:~/tool/sbt/bin:.
